gui:
  screenMode: 'halt'
  showCommandLog: false
  showBottomLine: false
  showListFooter: false
  portraitMode: 'always'
  theme:
    activeBorderColor:
      - '#B9AEDA'
      - bold
    inactiveBorderColor:
      - '#232323'
    selectedLineBgColor:
      - '#232323'
    cherryPickedCommitBgColor:
      - '#232323'
    cherryPickedCommitFgColor:
      - '#FFC799'
    unstagedChangesColor:
      - '#FFC799'
    defaultFgColor:
      - '#FFFFFF'
    searchingActiveBorderColor:
      - '#FFC799'
    optionsTextColor:
      - '#B9AEDA'
